package com.alpian.paymentws.dto;

import java.math.BigDecimal;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * DTO for Payment Intent API representation..
 */
@Schema(name = "PaymentIntentDTO", description = "Payment Intent data transfer object")
public class PaymentIntentDTO {
	@Schema(description = "Unique id generated at the payment intent creation by the system", example = "cb927a10-ffef-4568-9032-69e5b2215fbb")
	private String id;
	
	@Schema(description = "Customer identifier", example = "7e0e227e-0029-4369-80a7-ce5640b18879")
	private String customerId;

	@Schema(description = "Reference generated by payment provider for this payment intent", example = "pi_1R9mePCcn3AdJO8I6pnhapg1")
    private String pspReference;

    @Schema(description = "Amount that should be paid by the customer", example = "10.00")
    private BigDecimal amount;

    @Schema(description = "Currency used on the payment", example = "chf")
    private String currency;

    @Schema(description = "Capturable amount in case of pre authorization with future manual capture", example = "10.00")
    private BigDecimal amountCapturable;
    
    @Schema(description = "Amount actually paid by the customer", example = "10.00")
    private BigDecimal amountReceived;

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getCustomerId() {
		return customerId;
	}

	public void setCustomerId(String customerId) {
		this.customerId = customerId;
	}

	public String getPspReference() {
		return pspReference;
	}

	public void setPspReference(String pspReference) {
		this.pspReference = pspReference;
	}

	public BigDecimal getAmount() {
		return amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	public String getCurrency() {
		return currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	public BigDecimal getAmountCapturable() {
		return amountCapturable;
	}

	public void setAmountCapturable(BigDecimal amountCapturable) {
		this.amountCapturable = amountCapturable;
	}

	public BigDecimal getAmountReceived() {
		return amountReceived;
	}

	public void setAmountReceived(BigDecimal amountReceived) {
		this.amountReceived = amountReceived;
	}
}
